/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VpApp: typeof import('./.vitepress/vitepress/components/vp-app.vue')['default']
    VpDemo: typeof import('./.vitepress/vitepress/components/vp-demo/index.vue')['default']
    VpExample: typeof import('./.vitepress/vitepress/components/vp-demo/vp-example.vue')['default']
    VpSourceCode: typeof import('./.vitepress/vitepress/components/vp-demo/vp-source-code.vue')['default']
  }
}
